# These are supported funding model platforms

patreon: elvincode # Replace with a single Patreon username
buy_me_a_coffee: elvinkyungu # Replace with a single Buy Me a Coffee username
custom: ['https://elvin.vercel.app/'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
