name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint
      #- name: Lint
      #  run: npm run lint
      # Run tests
      # - name: Test
      # run: npm run test
      # Run build
      - name: Build
        run: npm run build
